### ISSUE TITLE
Communes pour Corse

### ISSUE THREAD

**Issue by Gulshan-Doorgah** [gregoiredavid/france-geojson#1]
Bonjour Grégoire,

Je ne peux pas trouver les données de communes pour Corse.

Peux-tu s'il te plait les mettre.

Merci :)

**Comment by gregoiredavid** [comment]
Les communes corses sont désormais disponibles dans la branche v2-dev : https://github.com/gregoiredavid/france-geojson/tree/v2-dev/corse
