### ISSUE TITLE
Add Packagist integration

### ISSUE THREAD

**Issue by jmleroux** [gregoiredavid/france-geojson#11]
Question relative à la PR #10 : idéalement, vous pourriez mettre en place le webhook avec packagist qui vous permettrait de mettre le package à jour automatquement à chaque pull request.
Cet article donne un exemple de ce qui peut être fait: http://blog.jgrossi.com/2013/creating-your-first-composer-packagist-package/

Bonne soirée,
JM

PS: si ce n'est pas possible ou si vous ne le souhaitez pas, ce n'est pas grave. Le seul fait d'avoir un `composer.json` dans un repo public permet déjà d'utiliser le gestionnaire de paquets Composer.

**Comment by gregoiredavid** [comment]
C'est fait : https://packagist.org/packages/gregoiredavid/france-geojson
