### ISSUE TITLE
Faire un sous-découpage des départements

### ISSUE THREAD

**Issue by cbek09** [gregoiredavid/france-geojson#15]
Bonjour @gregoiredavid, 

D'abord, je tenais à vous remercier car j'utilise vos fichiers en tant que bénévole dans le cadre d'un projet pour l'AFM-Téléthon. 
Dans le cas de notre association, certains départements sont découpés en plusieurs sous-ensemble (que nous appelons Coordination) ; J'aimerai donc pouvoir créer mes propres pseudo-département mais je ne sais pas comment m'y prendre.

Merci de votre aide,
Cyril

**Comment by gregoiredavid** [comment]
Bonjour et merci pour les encouragements !

Pour créer votre propre découpage géographique vous aurez besoin d'un logiciel SIG comme QGIS (gratuit et open-source) ou ArcGIS (payant). Ces outils vous permettront d'importer le tracé des départements et de dessiner "à la main" des frontières à l'intérieur de ceux-ci. Attention, la prise en main est un peu complexe mais il existe de nombreux guides et tutoriels en ligne.

Bon courage,
Grégoire
