### ISSUE TITLE
France avec DOM et TOM sur un même écran

### ISSUE THREAD

**Issue by cbek09** [gregoiredavid/france-geojson#18]
Bonjour,

Serait-il possible d'avoir une version les DOM et TOM à côté de la France pour pouvoir consulter l'ensemble (France + DOM + TOM) sur un même écran ?
L'idée est d'avoir les DOM et TOM à gauche de la France comme c'est le cas ici : http://mappemonde.mgm.fr/geovisu/119/

Merci,
Cyril

**Comment by gregoiredavid** [comment]
Bonjour,

Malheureusement non. Le geojson est un format d'encodage de données géospatiales, c'est à dire qu'il fournit simplement des coordonnées "brutes", sans s'occuper de leur affichage, un peu comme une base de donnée.

La mise en forme de ces données et leur disposition se fait avec d'autres outils, par exemple [d3.js](https://d3js.org/) dans l'exemple que vous donnez en lien.

**Comment by cbek09** [comment]
On créant une version qui ajoute un décalage sur les coordonnées "brutes" des DOM et des TOM cela permettrait de les "déplacer" pour qu'ils puissent être à côté de la France (dans l'Océan Atlantique).
Par exemple pour la Guyane, il faudrait remplacer les -54.xxxx par des -4.xxxx ou -5.xxx (soit un décalage de +49 ou +50) et les 5.xxxx par des 48.xxx.
Cela vous semble faisable ?

Merci
Cyril

**Comment by gregoiredavid** [comment]
Théoriquement oui, on peut "déplacer" un département en bidouillant toutes ses coordonnées simultanément, mais géographiquement ça ne voudrait rien dire donc ça ne rentre pas vraiment dans le cadre de ce dépôt git dont le but est de fournir des informations "géo-administratives" brutes qui puissent être utilisées aussi bien pour dessiner une carte que pour faire des calculs ou des opérations géographiques.

Vous pouvez tenter l'opération avec un logiciel SIG (comme qgis), mais je vous conseille plutôt d'utiliser les coordonnées réelles pour dessiner les polygones puis de les "re-disposer" avec un logiciel de traitement graphique, par exemple inkscape ou sketch si votre objectif est de créer une carte interactive vectorielle avec d3.js comme dans l'exemple donné en lien. Attention dans tous les cas à la cohérence de la [projection cartographique](https://fr.wikipedia.org/wiki/Projection_cartographique).

**Comment by cbek09** [comment]
Merci pour la réponse, je vais effectivement déplacer dynamiquement les polygones avec une extension Google Maps : https://github.com/bramus/google-maps-polygon-moveto

Merci
