### ISSUE TITLE
La base de données ADMIN EXPRESS COG remplace GEOFLA®

### ISSUE THREAD

**Issue by laurencedorman** [gregoiredavid/france-geojson#19]
Merci pour ce beau travail regroupant ces fichiers très utiles !

Je voulais remonter l'information que [GEOFLA ne sera plus mis à jour](http://professionnels.ign.fr/adminexpresscog) et il faut désormais se référer à [Admin Express](
http://professionnels.ign.fr/adminexpress) - toujours sur le site de l'IGN - afin d'avoir les versions plus récentes des fichiers .shp, .dbf et autre.

Je ferai un PR avec plaisir mais je ne connais pas votre méthode préférée de générer les fichiers geojson à partir des fichiers d'origine ?

**Comment by gregoiredavid** [comment]
Merci ! Je vais mettre à jour les fichiers prochainement. Avec Admin express il n'y a pas de gros changement dans les données elles-même manifestement, la principale nouveauté concerne la régularité des mises à jour et l'adoption du COG de l'INSEE (une excellente nouvelle d'ailleurs).
