### ISSUE TITLE
Nouvelles régions administratives

### ISSUE THREAD

**Issue by philippecarle** [gregoiredavid/france-geojson#2]
Si d'aventure le owner de ce repo avait sous le code la màj de la carto pour les nouvelles régions administratives, ce serait formidable ;)

**Comment by gregoiredavid** [comment]
Pas sous le coude malheureusement ! Mais j'ai bien l'intention de les ajouter à terme.

**Comment by philippecarle** [comment]
Je bosse dessus, j'en ai trouvé une version qui malheureusement compte un Feature pour chaque polygon d'une région ; il n'y a qu'à agglomérer tout ça en multipolygon… je te tiens au courant !
Je bosse sur une grosse bdd pour un projet perso, je pourrais ainsi disposer d'une base MySQL avec les données cartographiques stockées dans des champs de type SPATIAL. Ca marche plutôt pas mal donc je la partagerai sûrement.

**Comment by Tauop** [comment]
Salut,
Est-ce que vous pouvez partager la méthode GEOFlat -> geoJson ?

**Comment by bmenant** [comment]
@Tauop La base GEOFLA de l’IGN (http://professionnels.ign.fr/geofla) met à disposition des fichiers au format Shapefile. Tu peux les convertir en utilisant `ogr2ogr`. Un client Web est librement utilisable ici : http://ogre.adc4gis.com/ (attention, prend une archive Zip des shapefiles, et non ces derniers directement).

**Comment by philippecarle** [comment]
Je fais un petit up sur le sujet, je me remets à un projet pour lequel je vais avoir besoin d'une carto précise… si l'un d'entre vous a déjà fait le boulot, ce serait bête que j'y passe du temps. Si par contre ça peut être utile à tous, je ferais une PR avec le résultat ?

**Comment by philippecarle** [comment]
PR #5 ouverte

**Comment by gregoiredavid** [comment]
PR #5 mergée. Merci !
