### ISSUE TITLE
Script pour carte départements avec code couleur ? 

### ISSUE THREAD

**Issue by dhrou** [gregoiredavid/france-geojson#20]
Bonjour, 
Pour un projet perso (voir ci-dessous), je cherche un script python (notebook idéalement) pour afficher la carte des départements français avec un code de couleur, étant donné un vecteur avec une valeur numérique par département. Ca a l'air basique mais je n'ai rien trouvé pour l'instant. Il me semble que cette repo contient tous les éléments pour le faire.
Le projet perso, est d'analyser le fichier FANTOIR avec la liste de toutes les rues/voies de toutes les communes de france (mais sans info géographique) et d'extraire de la toponymie des infos sur la diffusion de pratique en agricultures. Extraire les infos du FANTOIR ne me pose pas de problème, j'aurai le nombre d'occurence de certains mots par départements. Il ne me manquera que la dernière étape, visualiser.
Merci d'avance pour toute indication utile.
David

**Comment by gregoiredavid** [comment]
Bonjour,

Je ne connais pas de librairies python dans ce domaine. Avec javascript je peux vous conseiller deux solutions :

- [Leaflet](http://leafletjs.com/) pour créer une carte "navigable" type google map. [Exemple](http://leafletjs.com/examples/choropleth/)
- [D3 JS](https://d3js.org/) pour créer une carte vectorielle au format SVG. [Exemple](https://bl.ocks.org/wboykinm/dbbe50d1023f90d4e241712395c27fb3)

Vous trouverez de très nombreux tutos en faisant une recherche sur google. Les données géographiques des départements métropolitains sont ici : https://github.com/gregoiredavid/france-geojson/blob/master/departements.geojson

**Comment by dhrou** [comment]
ok merci de votre réponse rapide.
Je suis résolument python, je continue à chercher. 
David
