### ISSUE TITLE
24 communes sont introuvable

### ISSUE THREAD

**Issue by tibs245** [gregoiredavid/france-geojson#21]
Bonjour,

Suite à un traitement des fichiers geojson afin de les liés a d'autre entités, je m'aperçois qu'il manque 24 communes dans les fichiers geojson.

Voici la listes des communes manquante

Code INSEE | Nom commune
---------|--------------------
97123 | SAINT BARTHELEMY
97127 | SAINT MARTIN
46048 | CALVIAC
15177 | SAINT CHRISTOPHE LES GORGES
15210 | SAINT REMY DE SALERS
59154 | COUDEKERQUE
68900 | TROIS EPIS
85279 | SALIGNY
36245 | VILLERS LES ORMES
41021 | LA BOSSE
41076 | ECOMAN
76037 | AUQUEMENSIL
86101 | FRONTENAY SUR DIVE
22297 | SAINT GOUENO
14265 | FERVAQUES
14187 | COULONCES
14388 | MAISONCELLES LA JOURDAN
14545 | ROULLOURS
14584 | ST GERMAIN DE TALLEVENDE
14717 | TRUTTEMER LE GRAND
14718 | TRUTTEMER LE PETIT
14730 | VAUDRY
27121 | BUS ST REMY
61313 | NOTRE DAME DU ROCHER

Savais-vous comment je peux trouver les découpes geojson de ces communes ? Ou quel moyen de les générer ? 

Je vous remercie d'avance pour vos réponses

Et GRAND MERCI @gregoiredavid pour ton repo qui est super utile et visiblement bien maintenu !

**Comment by gregoiredavid** [comment]
Bonjour,

Merci de le signaler ! D'après ce que je peux voir il s'agit de communes nouvelles, formées par un regroupement ou un redécoupage récent, que l'IGN n'a pas répercuté dans la dernière version de la base de donnée GEOFLA qui n'est plus mise à jour depuis quelques mois.

En attendant la mise à jour de ce repo à partir de la nouvelle base donnée de l'IGN "Admin Express" dans les prochains jours, vous pouvez retrouver les informations géographiques sur ces communes au format SHP directement sur le site de l'IGN : [admin express](http://professionnels.ign.fr/adminexpress) et les convertir en geojson via mapshaper ou un autre outil du même type (voir explications de ma méthode dans le fichier README.md)

Merci pour vos encouragements !
