### ISSUE TITLE
Position des communes

### ISSUE THREAD

**Issue by mycaule** [gregoiredavid/france-geojson#23]
Bonjour,

Je cherche à avoir un point représentatif de type `geometry.type == "Point"` pour les communes, qui soit à l'intérieur des [polygones disponibles ici](https://github.com/gregoiredavid/france-geojson/blob/master/departements/03-allier/communes-03-allier.geojson).

J'ai besoin pour mon application de ces deux informations simultanément (contour + point intérieur), je pense stocker le point intérieur pourra être stocké dans l'objet `properties`.

Pourriez-vous me suggérer une source d'information me permettant de recouper facilement les champs `properties.code` et `properties.nom` des fichiers que vous proposez ?

```javascript
"properties": {
  "code": "03252",
  "nom": "Saint-Pont"
}
```

Une autre solution que j'envisage éventuellement est de calculer une approximation avec cet algorithme.
https://blog.mapbox.com/a-new-algorithm-for-finding-a-visual-center-of-a-polygon-7c77e6492fbc

Voir également cette question que j'ai posé sur stackoverflow https://stackoverflow.com/questions/52467305/computing-the-center-of-gravity-of-a-geojson-polygon-using-jq

Je vais aussi vouloir faire la même chose pour les départements.

Merci.

**Comment by gregoiredavid** [comment]
Bonjour !

L'IGN ne fournit pas cette information dans admin express, il faudra donc effectivement la calculer par vos propres moyens. L'algorithme de mapbox est une bonne référence, vous pouvez également regarder du côté de [turf.js](http://turfjs.org/), plus particulièrement les méthodes [centroid](http://turfjs.org/docs#centroid) ou [centerOfMass](http://turfjs.org/docs#centerOfMass).

Attention, si vous cherchez la position du "centre-bourg" de chaque commune plutôt que le point central du polygone, je vous conseille de jeter un oeil aux données disponibles via [Open Street Map](https://www.openstreetmap.org/) en utilisant l'API [Overpass](https://wiki.openstreetmap.org/wiki/Overpass_API).

**Comment by mycaule** [comment]
Merci pour votre travail !

**Comment by mycaule** [comment]
Bonjour, je pense recouper avec cet API Open Data https://api-adresse.data.gouv.fr/search/?q=paris qui est plutôt simple d'utilisation, il suffit d'injecter le `properties.code` et `properties.nom` dans la requête

**Comment by gregoiredavid** [comment]
Merci pour l'info ! Effectivement je n'avais pas pensé à cette API, elle sera plus pratique à interroger qu'Open Street Map.
