### ISSUE TITLE
Départements d'outre-mer

### ISSUE THREAD

**Issue by sylvainbx** [gregoiredavid/france-geojson#3]
Les sources cartographiques pour les DOM (Guadeloupe, Martinique, Guyane, La Réunion, Mayotte) étant disponibles sur GEOFLA, j'aurais voulu savoir si vous aviez prévu de les ajouter ? Merci !

**Comment by jmleroux** [comment]
Je suis aussi intéressé

**Comment by lvl99** [comment]
+1

**Comment by jmleroux** [comment]
ping @philippecarle maybe

**Comment by philippecarle** [comment]
Je check ça ce soir et je vous dit ce que j'ai sous la main !

**Comment by gregoiredavid** [comment]
Merci @philippecarle !

Si tu ne les as pas sous la main j'ai prévu de travailler là dessus (et sur les autres issues) la semaine prochaine, j'aurai un peu de temps pour ça.

**Comment by gregoiredavid** [comment]
Les régions, départements, cantons, arrondissements et communes d'outre mer sont disponibles dans la branche v2-dev : https://github.com/gregoiredavid/france-geojson/tree/v2-dev

Attention, l'arborescence des fichiers sur cette branche n'est pas encore figée (en cours de réflexion).
