### ISSUE TITLE
Countour France métropolitaine seule (sans Corse)

### ISSUE THREAD

**Issue by ghost** [gregoiredavid/france-geojson#41]
Bonjour,
Merci pour cette belle collection,
Avez vous un contour fermé de l'exagone seul ?

J'ai besoin d'un seul contour fermé de la France du coup je sacrifie en dehors de l'exagone.
Merci encore !

**Comment by gregoiredavid** [comment]
Bonjour. Voilà : https://gist.github.com/gregoiredavid/c58659d1f062fccae5aede55debce784

Si vous examinez le fichier geojson "[metropole-version-simplifiee.geojson](https://raw.githubusercontent.com/gregoiredavid/france-geojson/master/metropole-version-simplifiee.geojson)", vous verrez qu'il contient un seul élément "Feature" de type "MultiPolygon". Dans la définition du format GeoJSON les coordonnées correspondent en fait à un array de plusieurs polygones. En l'occurence, dans ce fichier le premier polygone de la liste de coordonnées correspond à ce que vous recherchez, les autres sont des îles ou exclaves.

Bonne continuation,

**Comment by ghost** [comment]
Merci pour la réponse rapide !! Super
